### ISSUE TITLE
您好,请问输入框可以设置在底部吗

### ISSUE THREAD

**Issue by Tamrac-web** [jackyr/simple-chat-hub-extension#1]
Hello, can the input box be set at the bottom?

**Comment by jackyr** [comment]
> Hello, can the input box be set at the bottom?

Doing this would cause confusion with the input box of the chat page. I’ll consider better UI optimization solutions in the future.

**Comment by jackyr** [comment]
> Requesting support, Claude.

There's some limitations on integrating Claude. As an alternative, you can use the Claude bot in Poe.

**Comment by Tamrac-web** [comment]
thank you！
