### ISSUE TITLE
The code in the code box in Claude and ChatGPT cannot be copied by clicking the copy button

### ISSUE THREAD

**Issue by Windyskr** [jackyr/simple-chat-hub-extension#2]
<img width="110" alt="image" src="https://github.com/user-attachments/assets/48ba40b4-f27c-4e12-88dc-a2e48b5b31e5">
<img width="277" alt="image" src="https://github.com/user-attachments/assets/f7bc315f-d55e-429d-9792-fc21e5a56b4e">

**Comment by jackyr** [comment]
@Windyskr 
It will be fixed in v1.2.1. 
Thanks for your feedback!

**Comment by jackyr** [comment]
v1.2.1 published.
